# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-09 04:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='删除时间')),
                ('path', models.CharField(max_length=100, verbose_name='原图')),
            ],
            options={
                'verbose_name': '图片信息',
                'verbose_name_plural': '图片信息',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=20, verbose_name='残疾人姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='残疾人电话')),
                ('description', models.TextField(verbose_name='备注')),
                ('checkState', models.IntegerField(choices=[(0, '未审核'), (1, '已通过'), (-1, '未通过')], default=0, verbose_name='残疾人信息审核状态')),
                ('checkDescription', models.TextField(verbose_name='残疾人审核信息')),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Area', verbose_name='所属地区')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact', verbose_name='联络员')),
            ],
            options={
                'verbose_name': '残疾人入户情况',
                'verbose_name_plural': '残疾人入户情况',
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.Visit', verbose_name='入户'),
        ),
    ]
