# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-09 04:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(default='123456', max_length=11, verbose_name='密码')),
                ('description', models.TextField(verbose_name='备注')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('openId', models.CharField(max_length=50, null=True, verbose_name='openId')),
                ('bindState', models.CharField(choices=[('未绑定', '未绑定'), ('已绑定', '已绑定')], default='未绑定', max_length=6, verbose_name='绑定状态')),
                ('checkState', models.IntegerField(choices=[(0, '未审核'), (1, '已通过'), (-1, '未通过')], default=0, max_length=6, verbose_name='审核状态')),
                ('checkDescription', models.TextField(verbose_name='审核信息')),
            ],
            options={
                'verbose_name': '联络员',
                'verbose_name_plural': '联络员',
            },
        ),
    ]
