# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-09 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Area', verbose_name='所属地区'),
        ),
    ]
