# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-09 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='checkState',
            field=models.IntegerField(choices=[(0, '未审核'), (1, '已通过'), (-1, '未通过')], default=0, verbose_name='审核状态'),
        ),
    ]
