# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-09 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180109_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Area', verbose_name='所属地区'),
        ),
    ]
