# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-09 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20180109_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
    ]
